
lexicon = {}
lexicon["motionverbs"] = ["shuffle", "shuffles", "shuffled", "shuffling", "stumble", "stumbles", "stumbled",
						  "stumbling", "dodder", "dodders", "doddered", "doddering", "lope", "lopes", "loped",
						  "loping", "stroll", "strolls", "strolled", "strolling", "jog", "jogs", "jogged", "jogging",
						  "wander", "wanders", "wandered", "wandering", "amble", "ambles", "ambled", "ambling",
						  "saunter", "saunters", "sauntered", "sauntering", "strut", "struts", "strutted",
						  "strutting", "spurt", "spurts", "spurted", "spurting","stride","strides","strode",
						  "striding", "scurry", "scurries", "scurried", "scurrying", "dart", "darts", "darted",
						  "darting", "traipse", "traipses", "traipsed", "traipsing", "drift", "drifts", "drifted",
						  "drifting", "waltz", "waltzes", "waltzed", "waltzing", "sashay", "sashays", "sashayed",
						  "sashaying", "pace", "paces", "paced", "pacing", "sink", "sinks", "sunk", "sank", "sinking",
						  "rise", "rises", "rose", "risen", "rising", "move", "moves", "moved", "moving","walk",
						  "walks","walked","walking", "run", "runs", "ran", "running", "leap", "leaps", "leaped",
						  "leaping", "skip", "skips", "skipped", "skipping", "hop", "hops", "hopped", "hopping",
						  "jump", "jumps", "jumped", "jumping", "slide", "slides", "slid", "sliding", "slip", "slips",
						  "slipped", "slipping", "fall", "falls", "fallen", "fell", "falling", "tumble", "tumbles",
						  "tumbled", "tumbling", "roll", "rolls", "rolled", "rollling", "glide", "glid", "glides",
						  "glided", "gliding","plummet","plummets","plummeted","plummeting", "tumble", "tumbles",
						  "tumbled", "tumbling", "plunge", "plunges", "plunged", "plunging", "slump", "slumps",
						  "slumped", "slumping", "rebound", "rebounds", "rebounded", "rebounding", "dive", "dives",
						  "dived", "dove", "diven", "diving", "waver", "wavers", "wavered", "wavering", "soar",
						  "soars", "soared", "soaring", "retreat", "retreats", "retreated", "retreating", "wobble",
						  "wobbles", "wobbled", "wobbling","bounce","bounces","bounced","bouncing", "falter",
						  "falters", "faltered", "faltering", "seesaw", "seesaws", "seesawed", "seesawing"]
lexicon["thinkverbs"] = ["think",   "thinks",   "thought",   "thinking", "believe", "believes", "believed",
						 "believing", "expect", "expects", "expected", "expecting", "imagine", "imagines", "imagined",
						 "imagining", "anticipate", "anticipates", "anticipated", "anticipating", "surmise",
						 "surmises", "surmised", "surmising", "suppose", "supposes", "supposed", "supposing",
						 "conjecture", "conjectures", "conjectured", "conjecturing", "guess", "guesss", "guessed",
						 "guessing",   "conclude",   "concludes",   "concluded",   "concluding", "determine",
						 "determines", "determined", "determining", "reason", "reasons", "reasoned", "reasoning",
						 "reckon", "reckons", "reckoned", "reckoning", "figure", "figures", "figured", "figuring",
						 "opine", "opines", "opined", "opining", "deem", "deems", "deemed", "deeming", "assess",
						 "assesss", "assessed", "assessing", "judge", "judges", "judged", "judging", "hold", "holds",
						 "holdd", "holding",   "reckon",   "reckons",   "reckoned",   "reckoning", "consider",
						 "considers", "considered", "considering", "presume", "presumes", "presumed", "presuming",
						 "estimate", "estimates", "estimated", "estimating", "ponder", "ponders", "pondered",
						 "pondering", "reflect", "reflects", "reflected", "reflecting", "deliberate", "deliberates",
						 "deliberated", "deliberating", "meditate", "meditates", "meditated", "meditating",
						 "contemplate", "contemplates", "contemplated", "contemplating",   "muse",   "muses",
						 "mused",   "musing", "cogitate", "cogitates", "cogitated", "cogitating", "ruminate",
						 "ruminates", "ruminated", "ruminating", "brood", "broods", "broodd", "brooding",
						 "concentrate", "concentrates", "concentrated", "concentrating", "cerebrate", "cerebrates",
						 "cerebrated", "cerebrating", "consider", "considers", "considered", "considering",
						 "contemplate", "contemplates", "contemplated", "contemplating",   "deliberate",
						 "deliberates",   "deliberated",   "deliberating", "mull", "mulls", "mulled", "mulling",
						 "muse", "muses", "mused", "musing", "recall", "recalls", "recalled", "recalling", "remember",
						 "remembers", "remembered", "remembering", "recollect", "recollects", "recollected",
						 "recollecting", "imagine", "imagines", "imagined", "imagining", "picture", "pictures",
						 "pictured", "picturing", "visualize", "visualizes", "visualized", "visualizing",
						 "envisage",   "envisages",   "envisaged",   "envisaging", "envision", "envisions",
						 "envisioned", "envisioning", "dream", "dreams", "dreamed", "dreaming", "fantasize",
						 "fantasizes", "fantasized", "fantasizing", "suppose", "supposes", "supposed", "supposing",
						 "assume", "assumes", "assumed", "assuming", "imagine", "imagines", "imagined", "imagining",
						 "presume", "presumes", "presumed", "presuming", "hypothesis", "hypothesiss", "hypothesised",
						 "hypothesising",   "hypothesize",   "hypothesizes",   "hypothesized",   "hypothesizing",
						 "postulate", "postulates", "postulated", "postulating", "posit", "posits", "posited",
						 "positing", "evaluate", "evaluates", "evaluated", "evaluating", "judge", "judges", "judged",
						 "judging", "gauge", "gauges", "gauged", "gauging", "rate", "rates", "rated", "rating",
						 "estimate", "estimates", "estimated", "estimating", "appraise", "appraises", "appraised",
						 "appraising",   "analyse",   "analyses",   "analysed",   "analysing", "worry", "worries",
						 "worried", "worrying", "fret", "frets", "fretted", "fretting", "conceive", "conceives",
						 "conceived", "conceiving"]
lexicon["sayverbs"] = ["say", "says", "said", "saying", "speak", "speaks", "speaked", "speaking", "utter", "utters",
					   "uttered", "uttering", "voice", "voices", "voiced", "voicing", "pronounce", "pronounces",
					   "pronounced", "pronouncing", "vocalize", "vocalizes", "vocalized", "vocalizing", "declare",
					   "declares", "declared", "declaring", "state", "states", "stated", "stating", "announce",
					   "announces", "announced", "announcing", "remark", "remarks", "remarked", "remarking",
					   "observe", "observes", "observed", "observing", "mention", "mentions", "mentioned",
					   "mentioning", "comment", "comments", "commented", "commenting", "note", "notes", "noted",
					   "noting", "add", "adds", "added", "adding", "reply", "replys", "replyed", "replying",
					   "respond", "responds", "responded", "responding", "answer", "answers", "answered", "answering",
					   "rejoin", "rejoins", "rejoined", "rejoining", "whisper", "whispers", "whispered", "whispering",
					   "mutter", "mutters", "muttered", "muttering", "mumble", "mumbles", "mumbled", "mumbling",
					   "mouth", "mouths", "mouthed", "mouthing", "claim", "claims", "claimed", "claiming", "maintain",
					   "maintains", "maintained", "maintaining", "assert", "asserts", "asserted", "asserting", "hold",
					   "holds", "holdd", "holding", "insist", "insists", "insisted", "insisting", "contend",
					   "contends", "contended", "contending", "aver", "avers", "averred", "averring", "affirm",
					   "affirms", "affirmed", "affirming", "avow", "avows", "avowed", "avowing", "allege", "alleges",
					   "alleged", "alleging", "profess", "professs", "professed", "professing", "opine", "opines",
					   "opined", "opining", "asseverate", "asseverates", "asseverated", "asseverating", "express",
					   "expresss", "expressed", "expressing", "phrase", "phrases", "phrased", "phrasing",
					   "articulate", "articulates", "articulated", "articulating", "communicate", "communicates",
					   "communicated", "communicating", "convey", "conveys", "conveyed", "conveying", "verbalize",
					   "verbalizes", "verbalized", "verbalizing", "render", "renders", "rendered", "rendering",
					   "tell", "tells", "told", "telling", "reveal", "reveals", "revealed", "revealing", "divulge",
					   "divulges", "divulged", "divulging", "impart", "imparts", "imparted", "imparting", "disclose",
					   "discloses", "disclosed", "disclosing", "imply", "implies", "implied", "implying", "suggest",
					   "suggests", "suggested", "suggesting", "signify", "signifys", "signified", "signifying",
					   "denote", "denotes", "denoted", "denoting", "mean", "means", "meant", "meaning", "recite",
					   "recites", "recited", "reciting", "repeat", "repeats", "repeated", "repeating", "utter",
					   "utters", "uttered", "uttering", "deliver", "delivers", "delivered", "delivering", "perform",
					   "performs", "performed", "performing", "declaim", "declaims", "declaimed", "declaiming",
					   "orate", "orates", "orated", "orating", "indicate", "indicates", "indicated", "indicating",
					   "estimate", "estimates", "estimated", "estimating", "judge", "judges", "judged", "judging",
					   "guess", "guesss", "guessed", "guessing", "predict", "predicts", "predicted", "predicting",
					   "speculate", "speculates", "speculated", "speculating", "surmise", "surmises", "surmised",
					   "surmising", "conjecture", "conjectures", "conjectured", "conjecturing", "venture", "ventures",
					   "ventured", "venturing", "pontificate", "pontificates", "pontificated", "pontificating",
					   "propose", "proposes", "proposed", "proposing", "plead", "pleads", "pleading", "mutter",
					   "mutters", "muttered", "muttering", "murmur", "murmurs", "murmured", "murmuring", "mumble",
					   "mumbles", "mumbled", "mumbling", "whisper", "whispers", "whispered", "whispering", "hush",
					   "hushs", "hushed", "hushing", "grumble", "grumbles", "grumbled", "grumbling", "moan", "moans",
					   "moaned", "moaning", "complain", "complains", "complained", "complaining", "grouse", "grouses",
					   "groused", "grousing", "carp", "carps", "carped", "carping", "whine", "whines", "whined",
					   "whining", "bleat", "bleats", "bleated", "bleating", "gripe", "gripes", "griped", "griping",
					   "whinge", "whinges", "whinged", "whinging", "whine", "whines", "whined", "whining", "kvetch",
					   "kvetchs", "kvetched", "kvetching", "cry", "crys", "cried", "crying", "yelp", "yelps",
					   "yelped", "yelping", "call", "calls", "called", "calling", "shout", "shouts", "shouted",
					   "shouting", "howl", "howls", "howled", "howling", "yowl", "yowls", "yowled", "yowling", "wail",
					   "wails", "wailed", "wailing", "scream", "screams", "screamed", "screaming", "shriek",
					   "shrieks", "shrieked", "shrieking", "screech", "screechs", "screeched", "screeching", "squawk",
					   "squawks", "squawked", "squawking", "squeal", "squeals", "squealed", "squealing", "roar",
					   "roars", "roared", "roaring", "bawl", "bawls", "bawled", "bawling", "whoop", "whoops",
					   "whooped", "whooping", "holler", "hollers", "hollered", "hollering", "ululate", "ululates",
					   "ululated", "ululating", "laugh", "laughs", "laughed", "laughing", "chuckle", "chuckles",
					   "chuckled", "chuckling", "chortle", "chortles", "chortled", "chortling", "guffaw", "guffaws",
					   "guffawed", "guffawing", "giggle", "giggles", "giggled", "giggling", "titter", "titters",
					   "tittered", "tittering", "snigger", "sniggers", "sniggered", "sniggering", "snicker",
					   "snickers", "snickered", "snickering", "cackle", "cackles", "cackled", "cackling", "howl",
					   "howls", "howled", "howling", "roar", "roars", "roared", "roaring", "smile", "smiles",
					   "smiled", "smiling", "ridicule", "ridicules", "ridiculed", "ridiculing", "mock", "mocks",
					   "mocked", "mocking", "deride", "derides", "derided", "deriding", "scoff", "scoffs", "scoffed",
					   "scoffing", "jeer", "jeers", "jeered", "jeering", "sneer", "sneers", "sneered", "sneering",
					   "jibe", "jibes", "jibed", "jibing", "scorn", "scorns", "scorned", "scorning", "lampoon",
					   "lampoons", "lampooned", "lampooning", "satirize", "satirizes", "satirized", "satirizing",
					   "caricature", "caricatures", "caricatured", "caricaturing", "parody", "parodies", "parodied",
					   "parodying", "taunt", "taunts", "taunted", "taunting", "tease", "teases", "teased", "teasing",
					   "torment", "torments", "tormented", "tormenting", "expound", "expounds", "expounded",
					   "expounding", "declaim", "declaims", "declaimed", "declaiming", "preach", "preachs",
					   "preached", "preaching", "express", "expresss", "expressed", "expressing", "sermonize",
					   "sermonizes", "sermonized", "sermonizing", "moralize", "moralizes", "moralized", "moralizing",
					   "pronounce", "pronounces", "pronounced", "pronouncing", "lecture", "lectures", "lectured",
					   "lecturing", "perorate", "perorates", "perorated", "perorating"]
lexicon["implicativeverbs"] = ["manage", "manages", "managed", "managing", "forget", "forgets", "forgot",
							   "forgetting", "fail", "fails", "failed", "failing", "obey", "obeys", "obeyed",
							   "obeying", "succeed", "succeeds", "succeeded", "succeeding"]
lexicon["surprise"] = ["aback", "aghast", "amazed",
                       "appalled", "astonished", "astounded", "baffled", "bewildered", "blown", "flabbergasted",
                       "horrified", "mystified", "perplexed", "puzzled", "shocked", "stunned", "surprised",
                       "surprisingly", "appallingly", "astonishingly", "amazingly", "dismayed", "disconcerted",
                       "crestfallen", "dumbstruck", "dumbfounded", "elated", "speechless", "startled", "shocker",
                       "shockers", "scandalized", "repulsed", "relieved", "perturbed", "perplex", "absurd", "bummed",
                       "chuffed", "confounded", "confused", "devastated", "disappointed", "disgusted",
                       "disheartened", "distraught", "flummoxed", "exasperated", "flustered", "gobsmacked",
                       "annoyed", "livid", "ludicrous", "incensed", "incredulous", "astonish", "astound",
                       "awestruck", "awed", "baffling", "nonplussed", "mystifying", "mystifier", "wowed"]
lexicon["p1"] = ["i", "I", "me", "myself", "mine", "my"]
lexicon["p1pl"] = ["we", "us", "ourselves", "our", "ours"]
lexicon["p2"] = ["you", "yourself", "yourselves", "your", "yours"]
lexicon["p3"] = ["he", "she", "her", "hers", "his", "him", "himself",
                 "herself", "they", "their", "theirs", "themselves"]
#lexicon["ormaybenot"] = []
#lexicon["mood"] = []

lexicon["positive"] = ["a+",  "abound",  "abounds",  "abundance",  "abundant",  "accessable",  "accessible",
                       "acclaim",  "acclaimed",  "acclamation",  "accolade",  "accolades",  "accommodative",
                       "accomodative",  "accomplish",  "accomplished",  "accomplishment",  "accomplishments",
                       "accurate",  "accurately",  "achievable",  "achievement",  "achievements",  "achievible",
                       "acumen",  "adaptable",  "adaptive",  "adequate",  "adjustable",  "admirable",  "admirably",
                       "admiration",  "admire",  "admirer",  "admiring",  "admiringly",  "adorable",  "adore",
                       "adored",  "adorer",  "adoring",  "adoringly",  "adroit",  "adroitly",  "adulate",
                       "adulation",  "adulatory",  "advanced",  "advantage",  "advantageous",  "advantageously",
                       "advantages",  "adventuresome",  "adventurous",  "advocate",  "advocated",  "advocates",
                       "affability",  "affable",  "affably",  "affectation",  "affection",  "affectionate",
                       "affinity",  "affirm",  "affirmation",  "affirmative",  "affluence",  "affluent",  "afford",
                       "affordable",  "affordably",  "afordable",  "agile",  "agilely",  "agility",  "agreeable",
                       "agreeableness",  "agreeably",  "all-around",  "alluring",  "alluringly",  "altruistic",
                       "altruistically",  "amaze",  "amazed",  "amazement",  "amazes",  "amazing",  "amazingly",
                       "ambitious",  "ambitiously",  "ameliorate",  "amenable",  "amenity",  "amiability",
                       "amiabily",  "amiable",  "amicability",  "amicable",  "amicably",  "amity",  "ample",
                       "amply",  "amuse",  "amusing",  "amusingly",  "angel",  "angelic",  "apotheosis",  "appeal",
                       "appealing",  "applaud",  "appreciable",  "appreciate",  "appreciated",  "appreciates",
                       "appreciative",  "appreciatively",  "appropriate",  "approval",  "approve",  "ardent",
                       "ardently",  "ardor",  "articulate",  "aspiration",  "aspirations",  "aspire",  "assurance",
                       "assurances",  "assure",  "assuredly",  "assuring",  "astonish",  "astonished",
                       "astonishing",  "astonishingly",  "astonishment",  "astound",  "astounded",  "astounding",
                       "astoundingly",  "astutely",  "attentive",  "attraction",  "attractive",  "attractively",
                       "attune",  "audible",  "audibly",  "auspicious",  "authentic",  "authoritative",
                       "autonomous",  "available",  "aver",  "avid",  "avidly",  "award",  "awarded",  "awards",
                       "awe",  "awed",  "awesome",  "awesomely",  "awesomeness",  "awestruck",  "awsome",
                       "backbone",  "balanced",  "bargain",  "beauteous",  "beautiful",  "beautifullly",
                       "beautifully",  "beautify",  "beauty",  "beckon",  "beckoned",  "beckoning",  "beckons",
                       "believable",  "believeable",  "beloved",  "benefactor",  "beneficent",  "beneficial",
                       "beneficially",  "beneficiary",  "benefit",  "benefits",  "benevolence",  "benevolent",
                       "benifits",  "best",  "best-known",  "best-performing",  "best-selling",  "better",
                       "better-known",  "better-than-expected",  "beutifully",  "blameless",  "bless",  "blessing",
                       "bliss",  "blissful",  "blissfully",  "blithe",  "blockbuster",  "bloom",  "blossom",
                       "bolster",  "bonny",  "bonus",  "bonuses",  "boom",  "booming",  "boost",  "boundless",
                       "bountiful",  "brainiest",  "brainy",  "brand-new",  "brave",  "bravery",  "bravo",
                       "breakthrough",  "breakthroughs",  "breathlessness",  "breathtaking",  "breathtakingly",
                       "breeze",  "bright",  "brighten",  "brighter",  "brightest",  "brilliance",  "brilliances",
                       "brilliant",  "brilliantly",  "brisk",  "brotherly",  "bullish",  "buoyant",  "cajole",
                       "calm",  "calming",  "calmness",  "capability",  "capable",  "capably",  "captivate",
                       "captivating",  "carefree",  "cashback",  "cashbacks",  "catchy",  "celebrate",  "celebrated",
                       "celebration",  "celebratory",  "champ",  "champion",  "charisma",  "charismatic",
                       "charitable",  "charm",  "charming",  "charmingly",  "chaste",  "cheaper",  "cheapest",
                       "cheer",  "cheerful",  "cheery",  "cherish",  "cherished",  "cherub",  "chic",  "chivalrous",
                       "chivalry",  "civility",  "civilize",  "clarity",  "classic",  "classy",  "clean",  "cleaner",
                       "cleanest",  "cleanliness",  "cleanly",  "clear",  "clear-cut",  "cleared",  "clearer",
                       "clearly",  "clears",  "clever",  "cleverly",  "cohere",  "coherence",  "coherent",
                       "cohesive",  "colorful",  "comely",  "comfort",  "comfortable",  "comfortably",  "comforting",
                       "comfy",  "commend",  "commendable",  "commendably",  "commitment",  "commodious",  "compact",
                       "compactly",  "compassion",  "compassionate",  "compatible",  "competitive",  "complement",
                       "complementary",  "complemented",  "complements",  "compliant",  "compliment",
                       "complimentary",  "comprehensive",  "conciliate",  "conciliatory",  "concise",  "confidence",
                       "confident",  "congenial",  "congratulate",  "congratulation",  "congratulations",
                       "congratulatory",  "conscientious",  "considerate",  "consistent",  "consistently",
                       "constructive",  "consummate",  "contentment",  "continuity",  "contrasty",  "contribution",
                       "convenience",  "convenient",  "conveniently",  "convience",  "convienient",  "convient",
                       "convincing",  "convincingly",  "cool",  "coolest",  "cooperative",  "cooperatively",
                       "cornerstone",  "correct",  "correctly",  "cost-effective",  "cost-saving",  "counter-attack",
                       "counter-attacks",  "courage",  "courageous",  "courageously",  "courageousness",
                       "courteous",  "courtly",  "covenant",  "cozy",  "creative",  "credence",  "credible",
                       "crisp",  "crisper",  "cure",  "cure-all",  "cushy",  "cute",  "cuteness",  "danke",
                       "danken",  "daring",  "daringly",  "darling",  "dashing",  "dauntless",  "dawn",  "dazzle",
                       "dazzled",  "dazzling",  "dead-cheap",  "dead-on",  "decency",  "decent",  "decisive",
                       "decisiveness",  "dedicated",  "defeat",  "defeated",  "defeating",  "defeats",  "defender",
                       "deference",  "deft",  "deginified",  "delectable",  "delicacy",  "delicate",  "delicious",
                       "delight",  "delighted",  "delightful",  "delightfully",  "delightfulness",  "dependable",
                       "dependably",  "deservedly",  "deserving",  "desirable",  "desiring",  "desirous",  "destiny",
                       "detachable",  "devout",  "dexterous",  "dexterously",  "dextrous",  "dignified",  "dignify",
                       "dignity",  "diligence",  "diligent",  "diligently",  "diplomatic",  "dirt-cheap",
                       "distinction",  "distinctive",  "distinguished",  "diversified",  "divine",  "divinely",
                       "dominate",  "dominated",  "dominates",  "dote",  "dotingly",  "doubtless",  "dreamland",
                       "dumbfounded",  "dumbfounding",  "dummy-proof",  "durable",  "dynamic",  "eager",  "eagerly",
                       "eagerness",  "earnest",  "earnestly",  "earnestness",  "ease",  "eased",  "eases",  "easier",
                       "easiest",  "easiness",  "easing",  "easy",  "easy-to-use",  "easygoing",  "ebullience",
                       "ebullient",  "ebulliently",  "ecenomical",  "economical",  "ecstasies",  "ecstasy",
                       "ecstatic",  "ecstatically",  "edify",  "educated",  "effective",  "effectively",
                       "effectiveness",  "effectual",  "efficacious",  "efficient",  "efficiently",  "effortless",
                       "effortlessly",  "effusion",  "effusive",  "effusively",  "effusiveness",  "elan",  "elate",
                       "elated",  "elatedly",  "elation",  "electrify",  "elegance",  "elegant",  "elegantly",
                       "elevate",  "elite",  "eloquence",  "eloquent",  "eloquently",  "embolden",  "eminence",
                       "eminent",  "empathize",  "empathy",  "empower",  "empowerment",  "enchant",  "enchanted",
                       "enchanting",  "enchantingly",  "encourage",  "encouragement",  "encouraging",
                       "encouragingly",  "endear",  "endearing",  "endorse",  "endorsed",  "endorsement",
                       "endorses",  "endorsing",  "energetic",  "energize",  "energy-efficient",  "energy-saving",
                       "engaging",  "engrossing",  "enhance",  "enhanced",  "enhancement",  "enhances",  "enjoy",
                       "enjoyable",  "enjoyably",  "enjoyed",  "enjoying",  "enjoyment",  "enjoys",  "enlighten",
                       "enlightenment",  "enliven",  "ennoble",  "enough",  "enrapt",  "enrapture",  "enraptured",
                       "enrich",  "enrichment",  "enterprising",  "entertain",  "entertaining",  "entertains",
                       "enthral",  "enthrall",  "enthralled",  "enthuse",  "enthusiasm",  "enthusiast",
                       "enthusiastic",  "enthusiastically",  "entice",  "enticed",  "enticing",  "enticingly",
                       "entranced",  "entrancing",  "entrust",  "enviable",  "enviably",  "envious",  "enviously",
                       "enviousness",  "envy",  "equitable",  "ergonomical",  "err-free",  "erudite",  "ethical",
                       "eulogize",  "euphoria",  "euphoric",  "euphorically",  "evaluative",  "evenly",  "eventful",
                       "everlasting",  "evocative",  "exalt",  "exaltation",  "exalted",  "exaltedly",  "exalting",
                       "exaltingly",  "examplar",  "examplary",  "excallent",  "exceed",  "exceeded",  "exceeding",
                       "exceedingly",  "exceeds",  "excel",  "exceled",  "excelent",  "excellant",  "excelled",
                       "excellence",  "excellency",  "excellent",  "excellently",  "excels",  "exceptional",
                       "exceptionally",  "excite",  "excited",  "excitedly",  "excitedness",  "excitement",
                       "excites",  "exciting",  "excitingly",  "exellent",  "exemplar",  "exemplary",  "exhilarate",
                       "exhilarating",  "exhilaratingly",  "exhilaration",  "exonerate",  "expansive",
                       "expeditiously",  "expertly",  "exquisite",  "exquisitely",  "extol",  "extoll",
                       "extraordinarily",  "extraordinary",  "exuberance",  "exuberant",  "exuberantly",  "exult",
                       "exultant",  "exultation",  "exultingly",  "eye-catch",  "eye-catching",  "eyecatch",
                       "eyecatching",  "fabulous",  "fabulously",  "facilitate",  "fair",  "fairly",  "fairness",
                       "faith",  "faithful",  "faithfully",  "faithfulness",  "fame",  "famed",  "famous",
                       "famously",  "fancier",  "fancinating",  "fancy",  "fanfare",  "fans",  "fantastic",
                       "fantastically",  "fascinate",  "fascinating",  "fascinatingly",  "fascination",
                       "fashionable",  "fashionably",  "fast",  "fast-growing",  "fast-paced",  "faster",  "fastest",
                       "fastest-growing",  "faultless",  "fav",  "fave",  "favor",  "favorable",  "favored",
                       "favorite",  "favorited",  "favour",  "fearless",  "fearlessly",  "feasible",  "feasibly",
                       "feat",  "feature-rich",  "fecilitous",  "feisty",  "felicitate",  "felicitous",  "felicity",
                       "fertile",  "fervent",  "fervently",  "fervid",  "fervidly",  "fervor",  "festive",
                       "fidelity",  "fiery",  "fine",  "fine-looking",  "finely",  "finer",  "finest",  "firmer",
                       "first-class",  "first-in-class",  "first-rate",  "flashy",  "flatter",  "flattering",
                       "flatteringly",  "flawless",  "flawlessly",  "flexibility",  "flexible",  "flourish",
                       "flourishing",  "fluent",  "flutter",  "fond",  "fondly",  "fondness",  "foolproof",
                       "foremost",  "foresight",  "formidable",  "fortitude",  "fortuitous",  "fortuitously",
                       "fortunate",  "fortunately",  "fortune",  "fragrant",  "free",  "freed",  "freedom",
                       "freedoms",  "fresh",  "fresher",  "freshest",  "friendliness",  "friendly",  "frolic",
                       "frugal",  "fruitful",  "ftw",  "fulfillment",  "fun",  "futurestic",  "futuristic",
                       "gaiety",  "gaily",  "gain",  "gained",  "gainful",  "gainfully",  "gaining",  "gains",
                       "gallant",  "gallantly",  "galore",  "geekier",  "geeky",  "gem",  "gems",  "generosity",
                       "generous",  "generously",  "genial",  "genius",  "gentle",  "gentlest",  "genuine",
                       "gifted",  "glad",  "gladden",  "gladly",  "gladness",  "glamorous",  "glee",  "gleeful",
                       "gleefully",  "glimmer",  "glimmering",  "glisten",  "glistening",  "glitter",  "glitz",
                       "glorify",  "glorious",  "gloriously",  "glory",  "glow",  "glowing",  "glowingly",
                       "god-given",  "god-send",  "godlike",  "godsend",  "gold",  "golden",  "good",  "goodly",
                       "goodness",  "goodwill",  "goood",  "gooood",  "gorgeous",  "gorgeously",  "grace",
                       "graceful",  "gracefully",  "gracious",  "graciously",  "graciousness",  "grand",  "grandeur",
                       "grateful",  "gratefully",  "gratification",  "gratified",  "gratifies",  "gratify",
                       "gratifying",  "gratifyingly",  "gratitude",  "great",  "greatest",  "greatness",  "grin",
                       "groundbreaking",  "guarantee",  "guidance",  "guiltless",  "gumption",  "gush",  "gusto",
                       "gutsy",  "hail",  "halcyon",  "hale",  "hallmark",  "hallmarks",  "hallowed",  "handier",
                       "handily",  "hands-down",  "handsome",  "handsomely",  "handy",  "happier",  "happily",
                       "happiness",  "happy",  "hard-working",  "hardier",  "hardy",  "harmless",  "harmonious",
                       "harmoniously",  "harmonize",  "harmony",  "headway",  "heal",  "healthful",  "healthy",
                       "hearten",  "heartening",  "heartfelt",  "heartily",  "heartwarming",  "heaven",  "heavenly",
                       "helped",  "helpful",  "helping",  "hero",  "heroic",  "heroically",  "heroine",  "heroize",
                       "heros",  "high-quality",  "high-spirited",  "hilarious",  "holy",  "homage",  "honest",
                       "honesty",  "honor",  "honorable",  "honored",  "honoring",  "hooray",  "hopeful",
                       "hospitable",  "hot",  "hotcake",  "hotcakes",  "hottest",  "hug",  "humane",  "humble",
                       "humility",  "humor",  "humorous",  "humorously",  "humour",  "humourous",  "ideal",
                       "idealize",  "ideally",  "idol",  "idolize",  "idolized",  "idyllic",  "illuminate",
                       "illuminati",  "illuminating",  "illumine",  "illustrious",  "ilu",  "imaculate",
                       "imaginative",  "immaculate",  "immaculately",  "immense",  "impartial",  "impartiality",
                       "impartially",  "impassioned",  "impeccable",  "impeccably",  "important",  "impress",
                       "impressed",  "impresses",  "impressive",  "impressively",  "impressiveness",  "improve",
                       "improved",  "improvement",  "improvements",  "improves",  "improving",  "incredible",
                       "incredibly",  "indebted",  "individualized",  "indulgence",  "indulgent",  "industrious",
                       "inestimable",  "inestimably",  "inexpensive",  "infallibility",  "infallible",  "infallibly",
                       "influential",  "ingenious",  "ingeniously",  "ingenuity",  "ingenuous",  "ingenuously",
                       "innocuous",  "innovation",  "innovative",  "inpressed",  "insightful",  "insightfully",
                       "inspiration",  "inspirational",  "inspire",  "inspiring",  "instantly",  "instructive",
                       "instrumental",  "integral",  "integrated",  "intelligence",  "intelligent",  "intelligible",
                       "interesting",  "interests",  "intimacy",  "intimate",  "intricate",  "intrigue",
                       "intriguing",  "intriguingly",  "intuitive",  "invaluable",  "invaluablely",  "inventive",
                       "invigorate",  "invigorating",  "invincibility",  "invincible",  "inviolable",  "inviolate",
                       "invulnerable",  "irreplaceable",  "irreproachable",  "irresistible",  "irresistibly",
                       "issue-free",  "jaw-droping",  "jaw-dropping",  "jollify",  "jolly",  "jovial",  "joy",
                       "joyful",  "joyfully",  "joyous",  "joyously",  "jubilant",  "jubilantly",  "jubilate",
                       "jubilation",  "jubiliant",  "judicious",  "justly",  "keen",  "keenly",  "keenness",
                       "kid-friendly",  "kindliness",  "kindly",  "kindness",  "knowledgeable",  "kudos",
                       "large-capacity",  "laud",  "laudable",  "laudably",  "lavish",  "lavishly",  "law-abiding",
                       "lawful",  "lawfully",  "lead",  "leading",  "leads",  "lean",  "led",  "legendary",
                       "leverage",  "levity",  "liberate",  "liberation",  "liberty",  "lifesaver",  "light-hearted",
                       "lighter",  "likable",  "like",  "liked",  "likes",  "liking",  "lionhearted",  "lively",
                       "logical",  "long-lasting",  "lovable",  "lovably",  "love",  "loved",  "loveliness",
                       "lovely",  "lover",  "loves",  "loving",  "low-cost",  "low-price",  "low-priced",
                       "low-risk",  "lower-priced",  "loyal",  "loyalty",  "lucid",  "lucidly",  "luck",  "luckier",
                       "luckiest",  "luckiness",  "lucky",  "lucrative",  "luminous",  "lush",  "luster",
                       "lustrous",  "luxuriant",  "luxuriate",  "luxurious",  "luxuriously",  "luxury",  "lyrical",
                       "magic",  "magical",  "magnanimous",  "magnanimously",  "magnificence",  "magnificent",
                       "magnificently",  "majestic",  "majesty",  "manageable",  "maneuverable",  "marvel",
                       "marveled",  "marvelled",  "marvellous",  "marvelous",  "marvelously",  "marvelousness",
                       "marvels",  "master",  "masterful",  "masterfully",  "masterpiece",  "masterpieces",
                       "masters",  "mastery",  "matchless",  "mature",  "maturely",  "maturity",  "meaningful",
                       "memorable",  "merciful",  "mercifully",  "mercy",  "merit",  "meritorious",  "merrily",
                       "merriment",  "merriness",  "merry",  "mesmerize",  "mesmerized",  "mesmerizes",
                       "mesmerizing",  "mesmerizingly",  "meticulous",  "meticulously",  "mightily",  "mighty",
                       "mind-blowing",  "miracle",  "miracles",  "miraculous",  "miraculously",  "miraculousness",
                       "modern",  "modest",  "modesty",  "momentous",  "monumental",  "monumentally",  "morality",
                       "motivated",  "multi-purpose",  "navigable",  "neat",  "neatest",  "neatly",  "nice",
                       "nicely",  "nicer",  "nicest",  "nifty",  "nimble",  "noble",  "nobly",  "noiseless",
                       "non-violence",  "non-violent",  "notably",  "noteworthy",  "nourish",  "nourishing",
                       "nourishment",  "novelty",  "nurturing",  "oasis",  "obsession",  "obsessions",  "obtainable",
                       "openly",  "openness",  "optimal",  "optimism",  "optimistic",  "opulent",  "orderly",
                       "originality",  "outdo",  "outdone",  "outperform",  "outperformed",  "outperforming",
                       "outperforms",  "outshine",  "outshone",  "outsmart",  "outstanding",  "outstandingly",
                       "outstrip",  "outwit",  "ovation",  "overjoyed",  "overtake",  "overtaken",  "overtakes",
                       "overtaking",  "overtook",  "overture",  "pain-free",  "painless",  "painlessly",  "palatial",
                       "pamper",  "pampered",  "pamperedly",  "pamperedness",  "pampers",  "panoramic",  "paradise",
                       "paramount",  "pardon",  "passion",  "passionate",  "passionately",  "patience",  "patient",
                       "patiently",  "patriot",  "patriotic",  "peace",  "peaceable",  "peaceful",  "peacefully",
                       "peacekeepers",  "peach",  "peerless",  "pep",  "pepped",  "pepping",  "peppy",  "peps",
                       "perfect",  "perfection",  "perfectly",  "permissible",  "perseverance",  "persevere",
                       "personages",  "personalized",  "phenomenal",  "phenomenally",  "picturesque",  "piety",
                       "pinnacle",  "playful",  "playfully",  "pleasant",  "pleasantly",  "pleased",  "pleases",
                       "pleasing",  "pleasingly",  "pleasurable",  "pleasurably",  "pleasure",  "plentiful",
                       "pluses",  "plush",  "plusses",  "poetic",  "poeticize",  "poignant",  "poise",  "poised",
                       "polished",  "polite",  "politeness",  "popular",  "portable",  "posh",  "positive",
                       "positively",  "positives",  "powerful",  "powerfully",  "praise",  "praiseworthy",
                       "praising",  "pre-eminent",  "precious",  "precise",  "precisely",  "preeminent",  "prefer",
                       "preferable",  "preferably",  "prefered",  "preferes",  "preferring",  "prefers",  "premier",
                       "prestige",  "prestigious",  "prettily",  "pretty",  "priceless",  "pride",  "principled",
                       "privilege",  "privileged",  "prize",  "proactive",  "problem-free",  "problem-solver",
                       "prodigious",  "prodigiously",  "prodigy",  "productive",  "productively",  "proficient",
                       "proficiently",  "profound",  "profoundly",  "profuse",  "profusion",  "progress",
                       "progressive",  "prolific",  "prominence",  "prominent",  "promise",  "promised",  "promises",
                       "promising",  "promoter",  "prompt",  "promptly",  "proper",  "properly",  "propitious",
                       "propitiously",  "pros",  "prosper",  "prosperity",  "prosperous",  "prospros",  "protect",
                       "protection",  "protective",  "proud",  "proven",  "proves",  "providence",  "proving",
                       "prowess",  "prudence",  "prudent",  "prudently",  "punctual",  "pure",  "purify",
                       "purposeful",  "quaint",  "qualified",  "qualify",  "quicker",  "quiet",  "quieter",
                       "radiance",  "radiant",  "rapid",  "rapport",  "rapt",  "rapture",  "raptureous",
                       "raptureously",  "rapturous",  "rapturously",  "rational",  "razor-sharp",  "reachable",
                       "readable",  "readily",  "ready",  "reaffirm",  "reaffirmation",  "realistic",  "realizable",
                       "reasonable",  "reasonably",  "reasoned",  "reassurance",  "reassure",  "receptive",
                       "reclaim",  "recomend",  "recommend",  "recommendation",  "recommendations",  "recommended",
                       "reconcile",  "reconciliation",  "record-setting",  "recover",  "recovery",  "rectification",
                       "rectify",  "rectifying",  "redeem",  "redeeming",  "redemption",  "refine",  "refined",
                       "refinement",  "reform",  "reformed",  "reforming",  "reforms",  "refresh",  "refreshed",
                       "refreshing",  "refund",  "refunded",  "regal",  "regally",  "regard",  "rejoice",
                       "rejoicing",  "rejoicingly",  "rejuvenate",  "rejuvenated",  "rejuvenating",  "relaxed",
                       "relent",  "reliable",  "reliably",  "relief",  "relish",  "remarkable",  "remarkably",
                       "remedy",  "remission",  "remunerate",  "renaissance",  "renewed",  "renown",  "renowned",
                       "replaceable",  "reputable",  "reputation",  "resilient",  "resolute",  "resound",
                       "resounding",  "resourceful",  "resourcefulness",  "respect",  "respectable",  "respectful",
                       "respectfully",  "respite",  "resplendent",  "responsibly",  "responsive",  "restful",
                       "restored",  "restructure",  "restructured",  "restructuring",  "retractable",  "revel",
                       "revelation",  "revere",  "reverence",  "reverent",  "reverently",  "revitalize",  "revival",
                       "revive",  "revives",  "revolutionary",  "revolutionize",  "revolutionized",
                       "revolutionizes",  "reward",  "rewarding",  "rewardingly",  "rich",  "richer",  "richly",
                       "richness",  "right",  "righten",  "righteous",  "righteously",  "righteousness",  "rightful",
                       "rightfully",  "rightly",  "rightness",  "risk-free",  "robust",  "rock-star",  "rock-stars",
                       "rockstar",  "rockstars",  "romantic",  "romantically",  "romanticize",  "roomier",  "roomy",
                       "rosy",  "safe",  "safely",  "sagacity",  "sagely",  "saint",  "saintliness",  "saintly",
                       "salutary",  "salute",  "sane",  "satisfactorily",  "satisfactory",  "satisfied",
                       "satisfies",  "satisfy",  "satisfying",  "satisified",  "saver",  "savings",  "savior",
                       "savvy",  "scenic",  "seamless",  "seasoned",  "secure",  "securely",  "selective",
                       "self-determination",  "self-respect",  "self-satisfaction",  "self-sufficiency",
                       "self-sufficient",  "sensation",  "sensational",  "sensationally",  "sensations",  "sensible",
                       "sensibly",  "sensitive",  "serene",  "serenity",  "sexy",  "sharp",  "sharper",  "sharpest",
                       "shimmering",  "shimmeringly",  "shine",  "shiny",  "significant",  "silent",  "simpler",
                       "simplest",  "simplified",  "simplifies",  "simplify",  "simplifying",  "sincere",
                       "sincerely",  "sincerity",  "skill",  "skilled",  "skillful",  "skillfully",  "slammin",
                       "sleek",  "slick",  "smart",  "smarter",  "smartest",  "smartly",  "smile",  "smiles",
                       "smiling",  "smilingly",  "smitten",  "smooth",  "smoother",  "smoothes",  "smoothest",
                       "smoothly",  "snappy",  "snazzy",  "sociable",  "soft",  "softer",  "solace",  "solicitous",
                       "solicitously",  "solid",  "solidarity",  "soothe",  "soothingly",  "sophisticated",
                       "soulful",  "soundly",  "soundness",  "spacious",  "sparkle",  "sparkling",  "spectacular",
                       "spectacularly",  "speedily",  "speedy",  "spellbind",  "spellbinding",  "spellbindingly",
                       "spellbound",  "spirited",  "spiritual",  "splendid",  "splendidly",  "splendor",
                       "spontaneous",  "sporty",  "spotless",  "sprightly",  "stability",  "stabilize",  "stable",
                       "stainless",  "standout",  "state-of-the-art",  "stately",  "statuesque",  "staunch",
                       "staunchly",  "staunchness",  "steadfast",  "steadfastly",  "steadfastness",  "steadiest",
                       "steadiness",  "steady",  "stellar",  "stellarly",  "stimulate",  "stimulates",
                       "stimulating",  "stimulative",  "stirringly",  "straighten",  "straightforward",
                       "streamlined",  "striking",  "strikingly",  "striving",  "strong",  "stronger",  "strongest",
                       "stunned",  "stunning",  "stunningly",  "stupendous",  "stupendously",  "sturdier",  "sturdy",
                       "stylish",  "stylishly",  "stylized",  "suave",  "suavely",  "sublime",  "subsidize",
                       "subsidized",  "subsidizes",  "subsidizing",  "substantive",  "succeed",  "succeeded",
                       "succeeding",  "succeeds",  "succes",  "success",  "successes",  "successful",
                       "successfully",  "suffice",  "sufficed",  "suffices",  "sufficient",  "sufficiently",
                       "suitable",  "sumptuous",  "sumptuously",  "sumptuousness",  "super",  "superb",  "superbly",
                       "superior",  "superiority",  "supple",  "support",  "supported",  "supporter",  "supporting",
                       "supportive",  "supports",  "supremacy",  "supreme",  "supremely",  "supurb",  "supurbly",
                       "surmount",  "surpass",  "surreal",  "survival",  "survivor",  "sustainability",
                       "sustainable",  "swank",  "swankier",  "swankiest",  "swanky",  "sweeping",  "sweet",
                       "sweeten",  "sweetheart",  "sweetly",  "sweetness",  "swift",  "swiftness",  "talent",
                       "talented",  "talents",  "tantalize",  "tantalizing",  "tantalizingly",  "tempt",  "tempting",
                       "temptingly",  "tenacious",  "tenaciously",  "tenacity",  "tender",  "tenderly",  "terrific",
                       "terrifically",  "thank",  "thankful",  "thinner",  "thoughtful",  "thoughtfully",
                       "thoughtfulness",  "thrift",  "thrifty",  "thrill",  "thrilled",  "thrilling",  "thrillingly",
                       "thrills",  "thrive",  "thriving",  "thumb-up",  "thumbs-up",  "tickle",  "tidy",
                       "time-honored",  "timely",  "tingle",  "titillate",  "titillating",  "titillatingly",
                       "togetherness",  "tolerable",  "toll-free",  "top",  "top-notch",  "top-quality",  "topnotch",
                       "tops",  "tough",  "tougher",  "toughest",  "traction",  "tranquil",  "tranquility",
                       "transparent",  "treasure",  "tremendously",  "trendy",  "triumph",  "triumphal",
                       "triumphant",  "triumphantly",  "trivially",  "trophy",  "trouble-free",  "trump",  "trumpet",
                       "trust",  "trusted",  "trusting",  "trustingly",  "trustworthiness",  "trustworthy",
                       "trusty",  "truthful",  "truthfully",  "truthfulness",  "twinkly",  "ultra-crisp",
                       "unabashed",  "unabashedly",  "unaffected",  "unassailable",  "unbeatable",  "unbiased",
                       "unbound",  "uncomplicated",  "unconditional",  "undamaged",  "undaunted",  "understandable",
                       "undisputable",  "undisputably",  "undisputed",  "unencumbered",  "unequivocal",
                       "unequivocally",  "unfazed",  "unfettered",  "unforgettable",  "unity",  "unlimited",
                       "unmatched",  "unparalleled",  "unquestionable",  "unquestionably",  "unreal",
                       "unrestricted",  "unrivaled",  "unselfish",  "unwavering",  "upbeat",  "upgradable",
                       "upgradeable",  "upgraded",  "upheld",  "uphold",  "uplift",  "uplifting",  "upliftingly",
                       "upliftment",  "upscale",  "usable",  "useable",  "useful",  "user-friendly",
                       "user-replaceable",  "valiant",  "valiantly",  "valor",  "valuable",  "variety",  "venerate",
                       "verifiable",  "veritable",  "versatile",  "versatility",  "vibrant",  "vibrantly",
                       "victorious",  "victory",  "viewable",  "vigilance",  "vigilant",  "virtue",  "virtuous",
                       "virtuously",  "visionary",  "vivacious",  "vivid",  "vouch",  "vouchsafe",  "warm",
                       "warmer",  "warmhearted",  "warmly",  "warmth",  "wealthy",  "welcome",  "well",
                       "well-backlit",  "well-balanced",  "well-behaved",  "well-being",  "well-bred",
                       "well-connected",  "well-educated",  "well-established",  "well-informed",
                       "well-intentioned",  "well-known",  "well-made",  "well-managed",  "well-mannered",
                       "well-positioned",  "well-received",  "well-regarded",  "well-rounded",  "well-run",
                       "well-wishers",  "wellbeing",  "whoa",  "wholeheartedly",  "wholesome",  "whooa",  "whoooa",
                       "wieldy",  "willing",  "willingly",  "willingness",  "win",  "windfall",  "winnable",
                       "winner",  "winners",  "winning",  "wins",  "wisdom",  "wise",  "wisely",  "witty",  "won",
                       "wonder",  "wonderful",  "wonderfully",  "wonderous",  "wonderously",  "wonders",  "wondrous",
                       "woo",  "work",  "workable",  "worked",  "works",  "world-famous",  "worth",  "worth-while",
                       "worthiness",  "worthwhile",  "worthy",  "wow",  "wowed",  "wowing",  "wows",  "yay",
                       "youthful",  "zeal",  "zenith",  "zest",  "zippy"]

lexicon["dislike"] = ["abhor", "abhoring", "abhorred", "abhorrent", "abhorring", "abhors", "abominable",
                      "abomination", "abominations", "absurd", "absurdity", "absurdly", "aggravating",
                      "aggravatingly", "aggravation", "aggravations", "aggressive ", "agonised", "agonising",
                      "agonisingly", "agonized", "agonizing", "agonizingly", "agony", "amateurish ", "anemic",
                      "annoy ", "annoyance ", "annoyed", "annoying", "annoyingly", "annoys", "anti-climactic ",
                      "antsy", "appall", "appalled", "appalling", "appalls", "apprehensive ", "arduous ", "arrogant",
                      "arrogantly", "arse", "arsed", "asinine ", "atrocious", "atrocities", "awful", "awfulness",
                      "bad", "badly", "baffling ", "balderdash ", "bamboozled", "banal", "banality", "barbaric ",
                      "barf ", "below-standard", "bitch", "bitched", "bitches ", "bitching", "bitchy", "bizarre ",
                      "blah", "blaha", "bland", "blander", "blandest", "blatant ", "bloat", "bloated", "blockhead",
                      "bonehead", "bonkers", "boorish ", "bore", "bored", "bores", "boring", "bothering", "bothers",
                      "bothersome", "brainless ", "brazen", "brazenly ", "broken", "bullcrap", "bullied ",
                      "bullies ", "bullshit", "bullshite", "bummed", "bummer", "cancel", "cancelled", "cancelling",
                      "cancels", "careless", "carelessly", "catastrophic", "catastrophically ", "characterless",
                      "cheesier", "cheesiest", "cheesy", "childish", "childishly", "cliched ", "clichéd ",
                      "close-minded ", "clueless", "cluelessly", "cluelessness", "complain", "complained",
                      "complaining", "complains", "complaint ", "complicated ", "confuse ", "confuses ", "confused ",
                      "confusion ", "consternation ", "contemptible", "contemptibly", "contemptuous ", "contradicting",
                      "contradictory", "contradictions ", "contradicts ", "contraindication ", "controversial ",
                      "controversies ", "convoluted ", "cornier", "corniest", "corny", "corrupt", "corrupted",
                      "corrupting", "corruption ", "corrupts", "counter-intuitive", "counterintuitive", "crap",
                      "crappier", "crappiest", "crapping ", "crappy", "creepiest ", "creepy ", "cretin ",
                      "cringeworthy ", "crock ", "crummier", "crummiest", "crummy", "damage", "damages", "damaging",
                      "damn", "damned", "dead", "deader", "deadest", "deadly ", "death", "deceit", "deceitful",
                      "deceive", "deceived", "deceives", "deceiving", "deception ", "deceptive", "defeat",
                      "defeated", "defeating", "defeats", "defect ", "defective", "deficient", "defiling ",
                      "deluded ", "delusional ", "deplorable", "depress", "depressing", "depressingly", "derail ",
                      "despised", "despises", "detest", "detestable", "detested", "detesting", "detests",
                      "detriment", "detrimental", "detrimentally", "devastate", "devastated", "devastates",
                      "devastating", "dick", "dickhead ", "difficult", "difficulties", "difficulty", "dipshit",
                      "dirty", "dirtier", "dirtiest", "disappointed ", "disappointment ", "disapproval ",
                      "disconcerting ", "discouraging", "discredited", "disenchanted", "disenchantment ", "disgrace",
                      "disgraced", "disgraceful", "disgraces", "disgracing", "disgracingly", "disgust", "disgusted",
                      "disgusting", "disgustingly", "disgusts", "dislike", "disliked", "dislikes", "disliking",
                      "dismay ", "dismayed ", "dismaying", "dismayingly", "displeased", "displeases", "displeasing",
                      "displeasure", "disproportionate ", "disrespectful ", "disrespectfully ", "dissatisfactory",
                      "distaste ", "distasteful", "disturb", "disturbance", "disturbances", "disturbed",
                      "disturbing", "disturbingly", "disturbs", "dorkier", "dorkiest", "dorky", "douche", "douchy",
                      "douchebag", "douchebags", "downgrade", "downgraded", "downgrading", "drab", "drawback",
                      "drawbacks", "dread", "dreaded", "dreadful", "dreadfully", "dreading", "dreads", "dreary",
                      "dull", "duller", "dullest", "dumb", "dumbass", "dumber", "dumbest", "dump", "dumping",
                      "dumps", "embarrass", "embarrassed", "embarrasses", "embarrassing", "embarrassingly",
                      "embarrassment ", "erroneous", "erroneously", "error", "error-prone ", "errors", "errs",
                      "evil", "evil-doer", "evils", "exhausting ", "expensive", "expensively", "face-palm",
                      "facepalm", "fail", "failed", "failing", "fails", "failure", "failures", "fake ", "fallacious",
                      "false",
                      "falsehoods ", "falsification", "faltering ", "fault", "faults", "faulty", "feeble", "fiddly",
                      "fishy", "flagrant", "flagrantly", "flaw", "flawed", "flawing", "flaws", "flimsy ", "foolish",
                      "foolishness ", "fraud", "fraudulent", "frustrated", "frustrates", "frustrating",
                      "frustratingly", "frustration", "frustrations", "fuck", "fucked", "fucker", "fuckers",
                      "fuckface", "fucking", "fucko", "fucktard", "fucktards", "fuckwit ", "garbled ", "ghastly",
                      "gimmicky ", "glaring", "glaringly", "godawful", "grievances", "grieve", "grieves", "grievous",
                      "grievously", "grim", "grimmer", "grimmest", "gruesome", "gruesomely", "gruesomeness",
                      "grumpier", "grumpiest", "grumpy", "grumpyness", "hand-wringing", "handwringing",
                      "hardhearted", "hardheartedness", "hardliner", "harrowing", "hate", "hated", "hateful",
                      "hatefully", "hater", "haters", "hates", "hating", "hatred", "helpless", "helplessly",
                      "helplessness ", "hesitance", "hesitancy", "hesitate", "hesitated", "hesitant", "hesitantly",
                      "hesitatingly", "hideous", "hideously", "high-priced", "horrendous", "horrendously",
                      "horrible", "horribleness", "horribly", "horrid ", "horrific", "horrified", "horrifying ",
                      "horseshit ", "hostile", "hostility", "hurtful ", "hurting", "hurts", "idiot", "idiotic",
                      "idiots", "ignorant", "ignorantly", "ill-advised", "ill-favored", "illadvised", "illfavored",
                      "illogical ", "immature ", "immoral ", "impediment", "impediments ", "implausibility ",
                      "implausible ", "impose", "imposed", "imposes", "impractical ", "improprieties ", "improper",
                      "imprudent", "imprudently", "inadequate", "inadequately", "inane", "inappropriate",
                      "inappropriately", "inaudible", "inaudibly", "incompetent ", "inconsiderate ", "inconvenient",
                      "incorrect", "incorrectly", "indecent", "indecently", "ineffective", "inefficient", "inept",
                      "inferior", "inferiority", "infuriating ", "inordinately ", "insipid", "insufficient",
                      "insufficiently", "irrelevant", "irresponsible ", "irritate", "irritated", "irritates",
                      "irritating ", "irritatingly", "irritation", "irritations", "junk", "lame", "lamentable ",
                      "lamer", "lamest", "loathe", "loathed", "loathes", "loathing", "loathsome ", "looks dark",
                      "loser", "losers ", "lousy", "ludicrous", "lunacy ", "mean", "meaner", "meanest",
                      "meaningless", "mediocre", "miserable", "miserably", "misinformation", "misinformed",
                      "misrepresentations ", "misrepresentated", "misrepresents", "monotonous", "moron", "moronic",
                      "morons ", "mortified ", "naive ", "naively", "nastier", "nastiest", "nastiness ", "nasty",
                      "nauseated", "nauseates", "nauseating", "nauseous ", "naïve", "naïvely", "neglect ",
                      "neglected ", "neglectful ", "nonsense", "nonsensical ", "objectionable ", "off-putting ",
                      "offend", "offended", "offends", "offense", "offensive", "offensively", "offputting ",
                      "outraged", "outrageous", "outrageously", "outrages", "overdone", "overhyped", "overpaid",
                      "overpriced ", "overrated", "overvalued", "pathetic", "pathetically", "piss", "pitiful",
                      "pointless", "pointlessly", "pointlessness ", "pompous ", "poor", "poorer", "poorest",
                      "poorly", "pretentious ", "pricey", "problematic", "prohibitive", "prohibitively", "punishing",
                      "punishingly", "queasy ", "questionable", "questionably", "regretfully", "regrets",
                      "regretted", "regretting ", "reject", "rejected", "rejecting", "rejects", "reluctant",
                      "reluctantly", "repercussions", "repetitive", "reprehensible ", "repugnance", "repugnant",
                      "resent", "resented", "resentful", "resenting", "resentment", "resentments", "resents",
                      "ridiculous", "ridiculously", "ridiculousness ", "rip-off", "ripoff", "rubbish", "rude",
                      "rudely ", "ruder", "rudest", "scam", "scammed", "scamming", "scams", "scandal", "scandalous",
                      "scandals", "scum", "scummy ", "shabby ", "shame", "shameful", "shamefully", "sheesh",
                      "shitty", "simplistic ", "skeptical", "stressful ", "stupid", "stupider", "stupidest",
                      "stupidity", "stupidly ", "subpar ", "substandard", "suck ", "sucked ", "suckiness", "sucking",
                      "sucks", "sucky", "sux", "suxs", "tacky", "tasteless", "tedious", "tediously", "troubled",
                      "troubles", "troublesome", "troublesomely", "troubling", "tumultuous ", "uglier", "ugliest",
                      "ugliness", "ugly", "unacceptable", "unacceptably", "unappropriate", "unbearably ",
                      "uncomfortable", "uncomfortably", "underwhelming", "undesirable", "undrinkable ", "uneasy",
                      "unfavorable", "unfavorably", "unfavourable", "unfavourably", "unimaginative",
                      "unimaginatively", "unimpressive", "unimpressively", "uninformed", "unintelligent",
                      "unintelligently", "uninterested ", "uninteresting ", "unjust", "unlikable ", "unmemorable ",
                      "unnerving", "unpersuasive ", "unpleasant", "unpleasantly", "unpleasantness", "unreasonable",
                      "unreasonably", "unremarkable ", "unrewarding ", "unsafe ", "unsatisfactory",
                      "unsubstantiated", "unsuitable", "untasteful", "unwise", "unwisely", "upset", "upsets",
                      "upsetting", "useless", "uselessly", "vapid", "vex", "vexation", "vexed", "vexes", "vexing",
                      "vexingly", "vile ", "wanker ", "waste", "wasted", "wasteful", "wastes", "wasting", "weak",
                      "weaker", "weakest", "worrying", "worryingly", "worst", "worthless", "yuck", "yucky"]
lexicon["amplifyGrade"] = ["very", "awfully", "completely", "enormously", "entirely", "exceedingly", "excessively", "extremely",
                "greatly", "highly", "hugely", "immensely", "intensely", "particularly", "radically", "significantly",
                "strongly", "substantially", "totally", "utterly", "vastly"]

lexicon["amplifyTruly"] = ["absolutely", "definitely", "famously", "genuinely", "immaculately", "overly", "perfectly", "really",
                "severely", "surely", "thoroughly", "truly", "undoubtedly"]

lexicon["amplifySurprise"] = ["amazingly", "dramatically", "drastically", "emphatically", "exceptionally", "extraordinarily",
                   "fantastically", "horribly", "incredibly", "insanely", "phenomenally", "remarkably", "ridiculously",
                   "strikingly", "surprisingly", "terribly", "unusually", "wildly", "wonderfully",
                              "amazing", "dramatic", "drastic", "emphatic", "exceptional",
                              "extraordinary",
                              "fantastic", "incredible", "phenomenal", "remarkable",
                              "striking", "surprising","unusual"
                              ]

lexicon["but"] = ["but"]

lexicon["negation"] = ["no", "none", "never", "not", "n't", "neither", "nor"]
lexicon["amplifier"] = lexicon["amplifyGrade"] + lexicon["amplifySurprise"] + lexicon["amplifyTruly"]

lexicon["hedgelist"] = ["apparently", "appear", "around", "basically", "effectively", "evidently",
                        "fairly", "generally",
             "hopefully", "largely", "likely", "mainly", "maybe", "mostly", "overall", "perhaps", "presumably",
             "probably", "quite", "rather", "somewhat", "supposedly", "possibly", "doubtfully", "arguably", "often",
             "unlikely", "usually", "sometimes", "certainly", "definitely", "clearly", "conceivably", "apparent",
             "certain", "possible", "presumed", "probable", "putative", "supposed", "doubtful", "appear", "assume",
             "estimate", "indicate", "infer", "intend", "presume", "propose", "seem", "speculate", "suggest", "suppose",
             "tend", "doubt"]

lexicon["interjection"] = ["oops", "hello", "yea", "um", "ow", "aw", "huh", "em", "oo", "goo", "ugh", "oh", "eh", "hi",
                           "yeah", "ouch", "er", "hey", "uh", "uhhuh", "pow", "zowie", "zow", "lol", "hahah", "haha",
                           "uh-huh", "cmon", "c'mon", "pffft", "uhhhh", "hmm", "hmmm", "hm", "omg", "ok", "wow", "ok",
                           "tbh", "aw", "oops", "wtf", "pls", "ya", "arrr", "woohoo", "yep", "yay", "thx"]

lexicon["timeadverbial"] = ["afterwards", "again", "earlier", "early", "eventually", "formerly", "immediately",
                            "initially", "instantly", "late", "lately", "later", "momentarily", "now", "nowadays",
                            "once", "originally", "presently", "previously", "recently", "shortly", "simultaneously",
                            "soon", "subsequently", "today", "tomorrow", "tonight", "yesterday"]

lexicon["excitement"] = ["excited", "fun", "exciting"]

lexicon["embarrassing"] = ["embarrassing", "dorky", "ridiculous"]

lexicon["boredom"] = ["bereft", "bored", "boring", "cautious", "cautiously", "cheerless", "cheerlessly",
                      "cheerlessness", "deject", "dejected", "depress", "depressed", "depressing", "depression",
                      "depressive", "desolate", "desolation", "despair", "despairingly", "dingy", "discourage",
                      "discouraged", "dishearten", "disheartened", "disheartening", "dismal", "dismay", "dispirit",
                      "dispirited", "dispiritedness", "dispiriting", "distressed", "doleful", "dismayed", "downcast",
                      "despairing", "downhearted", "downheartedness", "downtrodden", "drab", "drear", "dreary",
                      "dull", "duller", "dullest", "forlorn", "forlornly", "forlornness", "gloom", "gloomful",
                      "gloomily", "gloominess", "glooming", "gloomy", "glum", "godforsaken", "grim", "hapless",
                      "hesitant", "hesitantly", "hesitate", "hesitated", "hesitates", "hesitating", "hesitatingly",
                      "hesitation", "hesitations", "insecure", "insecurity", "joyless", "joylessly", "joylessness",
                      "loneliness", "lonely", "lorn", "melancholic", "melancholy", "miserable", "miserably",
                      "misery", "mournful", "mournfully", "mournfulness", "mourning", "pathetic", "piteous",
                      "pitiable", "pitiful", "pitying", "plain", "plainer", "plainest", "plaintive", "plaintively",
                      "plaintiveness", "poor", "poorer", "poorest", "regret", "regretful", "remorse", "remorseful",
                      "remorsefully", "repent", "repentance", "repentant", "repentantly", "sad", "sadden",
                      "saddening", "sadly", "sadness", "self-pity", "shamed", "shamefaced", "skeptical",
                      "skeptically", "skeptics", "somberness", "somber", "unhappiness", "unhappy", "woeful",
                      "woefully", "woefulness", "worryingly", "worrysome", "wretched"]

lexicon["insecure"] = ["afraid", "aghast", "agonized", "alarm", "alarmed", "alarming", "alarmingly", "angst",
                       "anxiety", "anxious", "anxiously", "appal", "appall", "appalled", "appallingly",
                       "apprehension", "apprehensive", "apprehensively", "apprehensiveness", "atrocious",
                       "atrociously", "atrocities", "attrocious", "attrocities", "awe", "awed", "awful", "bashfully",
                       "cautious", "cautiously", "consternation", "cowardly", "cowed", "cower",
                       "creepy", "daunt", "daunting", "defenseless", "diffidence", "diffident", "diffidently", "dire",
                       "direful", "dismay", "dismayed", "doom",  "gloom", "dread", "dreaded", "dreadful", "dreadfully",
                       "dreading", "exposed", "fainthearted", "fawn", "fear", "feared", "fearful", "fearfully",
                       "fearfulness", "fearing", "fearingly", "fears", "fearsome", "fidgety", "foreboded", "foreboding",
                       "freaked", "fright", "frighten", "frighten away", "frighten off", "frightened", "frightening",
                       "frighteningly", "frightful", "frighting", "frightingly", "grovel", "gruesome", "hangdog",
                       "hangdogged", "hauntingly", "horrible", "horrid", "horridly", "horrific", "horrifically",
                       "horrified", "horrify", "horrifying", "horrifyingly", "horror",
                       "horror-stricken", "horror-struck",
                       "hysteria", "hysterical", "hysterically", "insecure", "intimidate", "intimidated",
                       "intimidating", "intimidatingly", "intimidation", "menaced", "menacing", "nerve-racking",
                       "nerve-wracking", "nervous", "nervously", "panic", "panic-attack", "panic-stricken",
                       "panic-struck", "panicked", "panicking", "panicky", "petrified", "phobic", "pitilessness",
                       "premonition", "presage", "presentiment", "quaking", "scare", "scare-away", "scare-off",
                       "scared", "scarey", "scarily", "scaring", "scary", "shivery", "shocked", "shuddery", "spooky",
                       "suspense", "suspenseful", "suspensive", "terrible", "terrified", "terror", "terrorised",
                       "terrorising", "terrorized", "terrorizing", "threat", "threaten", "threatened", "threatening",
                       "timid", "timidity", "timidly", "timidness", "timorous", "timorously", "timorousness",
                       "trembling", "tremulous", "trepid", "trepidation", "trepidly", "uneasy", "phobia", "ambivalent",
                       "anxieties", "baffled", "bothered", "bothering", "bothers", "bothersome", "caution",
                       "cautionary", "cautioning", "cautions", "chance", "chanced", "chances", "chancing",
                       "clueless", "cluelessness", "conceivable", "conceivably", "concern", "concerned", "concerns",
                       "confuse", "confused", "confuses", "confusing", "confusingly", "confusion", "could",
                       "debatable", "debatably", "debateable", "desperate", "desperately", "desperation", "dicey",
                       "disagree", "disbelief", "disbeliving", "disconcert", "disconcerted", "disconcerting",
                       "disconcertingly", "distress", "distressed", "distressing", "distressingly", "disturb",
                       "disturbed", "disturbing", "disturbingly", "disturbs", "doubt", "doubted", "doubters",
                       "doubtful", "doubtfully", "doubtfulness", "doubts", "dread", "dreading", "dreads", "dubious",
                       "dubiousness", "dunno", "fathom", "fret", "frets", "fretted", "fretting", "guess", "hesitant",
                       "hesitantly", "hesitate", "hesitated", "hesitates", "hesitating", "hesitatingly",
                       "hesitation", "hesitations", "hesitent", "iffy", "incredulous", "incredulously", "insecure",
                       "insecurities", "insecurity", "irresolute", "kinda", "kindof", "maybe", "might", "mystified",
                       "ponder", "pondered", "pondering", "ponderings", "possibilities", "possibility", "possible",
                       "possibly", "potential", "potentialities", "potentiality", "potentially", "presume",
                       "presumed", "presumes", "probably", "puzzled", "questionable", "questionably", "questioning",
                       "questioningly", "reckon", "reckon", "reckons", "reluctance", "reluctant", "rumor", "rumored",
                       "rumoring", "rumors", "rumour", "rumoured", "rumouring", "rumours", "sketchy", "somewhat",
                       "sorta", "speculate", "speculated", "speculates", "speculation", "speculations", "suspicions",
                       "tense", "tensed", "tenses", "tensing", "tension", "tensions", "theorize", "theorized",
                       "trouble", "troubled", "troubles", "troublesome", "troubling", "troublingly", "uncertain",
                       "uncertainly", "uncertainties", "uncertainty", "unclear", "unclearly", "unconvinced",
                       "unconvincingly", "undecided", "uneasiness", "uneasy", "unlikely", "unreliable", "unreliably",
                       "unsettled", "unsure", "upset", "upsets", "upsetting", "vague", "vaguely", "vagueness",
                       "vexatious", "vexed", "vexes", "vexing", "wonder", "wondered", "wondering", "worried",
                       "worriedly", "worries", "worrisome", "worry", "worrying", "worryingly", "worrys", "worrysome"]


lexicon["hate"] = ["abhor", "abhorred", "abhorring", "abhors", "aversion", "deride", "despise", "despised",
                   "despises", "despising", "detest", "detested", "detesting", "detests", "disapprove",
                   "disapproved", "disapproves", "disapproving", "disdain", "disdained", "disdaining", "disdains",
                   "disgusted", "dislike", "disliked", "dislikes", "disliking", "eschew", "eschewed", "eschewes",
                   "eschewing", "hate", "hated", "hates", "hating", "hostile", "loath", "loathed", "loathes",
                   "loathesome", "loathing", "repelled", "repellent", "repulsive", "revile", "reviled", "reviles",
                   "reviling", "scorn", "scorned", "scorning", "scorns", "shun", "shunned", "shunning", "shuns"]


lexicon["profanity"] = ["a-hole", "a-holes", "a.ss", "apeshit", "arse", "arsed", "arsehole", "arseholes", "arses",
                        "ass", "assed", "asses", "asshat", "asshats", "asshole", "assholes", "whore", "balls",
                        "baloney", "barf", "bastard", "bastards", "biatch", "bitch", "bitches", "bitchy", "bollocks",
                        "bollox", "bs", "bugger", "bullcrap", "bullshit", "clusterfuck", "cock", "cocks", "crap",
                        "crapola", "crappy", "cuckold", "cuck", "cunt", "cunts", "dammit", "damn", "damned", "dang",
                        "danged", "darn", "darned", "dick", "dickbag", "dickhead", "dickish", "dildo", "dipshit",
                        "dipshits", "dogshit", "dolt", "douche", "douchebag", "douchebags", "douches", "douchey",
                        "dumbass", "dumbasses", "dumbfuck", "effin", "effing", "f-ing", "faggot", "faggots", "fanny",
                        "farking", "fck", "fcking", "fcuking", "feck", "feckin", "fecking", "fgt", "af", "fkin",
                        "fking", "fkn", "fricken", "frickin", "fricking", "friggen", "friggin", "frigging", "fuck",
                        "fucken", "fucker", "fuckers", "fuckin", "fucking", "moron", "fucks", "fucktard",
                        "fucktards", "fuckwad", "fuckwit", "fuk", "fukin", "fuking", "hoe", "hoes", "horseshit",
                        "jerk", "jerked", "jerking", "lame", "libtard", "libtards", "mofo", "moronic", "morons",
                        "motherfucker", "motherfuckers", "motherfucking", "nigga", "niggas", "niggaz", "nigger",
                        "niggers", "pervert", "perverts", "phuck", "piss", "pissant", "poo", "poop", "prick",
                        "pricks", "pussies", "pussy", "rape", "rapey", "retarded", "retards", "s--t", "scat",
                        "schmuck", "scumbag", "scumbags", "sh-t", "sh1t", "shiit", "shit", "shite", "shitfaced",
                        "shitheads", "shithole", "shitshow", "shitstain", "shitstorm", "shitter", "shitty", "shyte",
                        "skank", "slut", "slutty", "sodding", "stfu", "stinkin", "tit", "tits", "turd", "turds",
                        "twat", "twats", "wank", "wanker", "wankers", "whore", "whores", "whoring", "wuss"]

lexicon["love"] = ["gorgeous", "allure", "allured", "allures", "alluring", "alluringly", "arouse", "aroused", "arouses",
                   "arousing", "arousingly", "attract", "attractance", "attractant", "attractants", "attracted",
                   "attraction", "attractions", "attractive", "attractively", "attractiveness", "attracts", "bangin",
                   "beatiful", "beautiful",
                   "beautifull", "beautifully", "booty", "bootylicious", "charismatic", "crave", "craving",
                   "cravings", "cuddlier", "cuddliest", "cuddly", "cute", "cutely", "cuteness", "cuter", "cutest",
                   "dashy", "delectable", "delight", "dishy", "entice", "enticed", "enticement", "enticements",
                   "entices", "enticing", "enticingly", "erotic", "erotically", "excite", "excited", "excitedly",
                   "excitement", "excites",
                   "exciting", "excitingly", "exquisite", "fancy", "fancying", "finer", "finest", "flirt", "flirt",
                   "flirtation", "flirtations", "flirtatious", "flirtatiously", "flirted", "flirts", "flirty",
                   "fond", "fonder", "fondest", "foxy", "foxylutely", "freakalicious", "freakaliciously", "fuxy",
                   "glamorous", "good", "goodlooking", "good-looking",
                   "gorgeous", "gorgeously", "gorgeousness", "hornier", "horniest", "horny", "hot", "hotness", "hotter",
                   "hunk", "hunky",
                   "hottest", "juicy", "kinkier", "kinkiest", "kinky", "kissable", "lewd", "lewdness", "love", "loved",
                   "loveliness", "lovely", "loves", "lovesick", "lovestruck", "lovingly", "luscious", "lust",
                   "lusted", "luster", "lustful", "lustfully", "lusts", "naughtier", "naughtiest", "naughty",
                   "nice-looking", "nicely", "nicer", "passion", "passionate", "passionately", "passione",
                   "pleasure", "pleasured", "pleasures", "pleasuring", "pleasuringly", "pouty", "racy", "randy",
                   "raunchy", "red-hot", "redhot", "rocks",
                   "rodder", "satisfaction", "satisfied", "satisfy", "satisfying", "seduce", "seduced", "seduces",
                   "seducingly", "seduction", "seductive", "seductively", "seductiveness", "seminude", "sensual",
                   "sensuality", "sensually", "sensuous", "sensuously", "sensuousness", "sex", "sexed", "sexier",
                   "sexiest", "sexkitten", "sexpot", "sexual", "sexuales", "sexualised", "sexually", "sexxxy",
                   "sexxy", "sexy", "smokin", "spicy", "sssssssssssmokin", "steamingly", "steamy", "stunna",
                   "stunner", "stunners", "stunning", "sumptuous", "sumptuously", "sumptuousness", "sweet",
                   "sweetest", "sweetheart", "sweethearts", "tantalize",                                                                                                                                                                                                                                                                                                                                                                          "tantalized", "tantalizes", "tantalizing", "tantalizingly", "tender", "tendered", "tenderest", "voluptuous",
                   "voluptuously", "voluptuousness", "wild", "wilder", "wildest", "wildly"]

lexicon["placeadverbial"] = ["aboard", "above", "abroad", "across", "ahead", "alongside", "around", "ashore",
                             "astern", "away", "behind", "below", "beneath", "beside", "downhill", "downstairs",
                             "downstream", "east", "far", "hereabouts", "indoors", "inland", "inshore", "inside",
                             "locally", "near", "nearby", "north", "nowhere", "outdoors", "outside", "overboard",
                             "overland", "overseas", "south", "underfoot", "underground", "underneath", "uphill",
                             "upstairs", "upstream", "west"]

lexicon["thank"] = ["thank", "thanks", "grateful", "thankful", "gratefully", "thx"]

lexicon["women"] = ["female", "lady", "ladies", "woman", "women", "she", "her", "herself", "females"]
lexicon["family"] = ["children", "sons", "daughters", "sisters", "brothers", "husbands", "wives", "mothers", "fathers",
                     "grandfathers", "grandmothers", "uncles", "aunts", "cousins", "nephews", "nieces",
                     "siblings",
                     "child", "son", "daughter", "sister", "brother", "husband", "wife", "mother", "father",
                     "grandfather", "grandmother", "grandpa", "grandma", "uncle", "aunt", "cousin", "nephew", "niece",
                     "sibling",
                     "child's", "son's", "daughter's", "sister's", "brother's", "husband's", "wife's", "mother's",
                     "father's",
                     "grandfather's", "grandmother's", "grandpa's", "grandma's", "uncle's", "aunt's", "cousin's",
                     "nephew's", "niece's",
                     "sibling's",
                     "childrens'", "sons'", "daughters'", "sisters'", "brothers'", "husbands'", "wives'", "mothers'",
                     "fathers'",
                     "grandfathers'", "grandmothers'", "uncles'", "aunts'", "cousins'", "nephews'", "nieces'",
                     "siblings'",
                     "family", "families", "families'", "family's"
                     ]
